/* eslint-disable @next/next/no-img-element */
import { useRouter } from 'next/router'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Ebook.module.scss'
import validator from 'validator';
import Countdown from 'react-countdown';
import axios from 'axios';

export default function Ebook() {
  const router = useRouter()
  const { token } = router.query

  const handleSubmit = function (e) {
    e.preventDefault();
    let email = document.querySelector('#email').value;

    if (!email) { document.querySelector('#error-email').innerHTML = 'Não pode ficar em branco'; return }
    if (!validator.isEmail(email)) { document.querySelector('#error-email').innerHTML = 'Email inválido'; return }

    sendEmail(token, email)
  }

  const onChangeEmail = function () {
    document.querySelector('#error-email').innerHTML = ''
  }

  const getTime = function () {
    let d = new Date
    let hora = d.getHours()
    let minutos = d.getMinutes()
    let milisec = (3600000 * (24 - hora)) - (minutos * 60000)
    return milisec
  }

  async function sendEmail(_token, _email) {
    let url = 'http://localhost:3003/api/v1/ebooks/enviar_ebook'
    try {
      await axios.post(url, { token: _token, email: _email });
      router.push('/ebook/sucesso')
    } catch (error) {
      console.error(error);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Download E-book Grátis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.imgHeader}>
        <img src="/images/header-mari.jpg" alt="image" className={styles.image}></img>
      </header>

      <main className={styles.formulario}>
        <img src="/images/ebook.jpg" alt="image" className={styles.image}></img>
        <div className={styles.boxFormulario}>
          <div>
            <h1>10 Dicas para ganhar dinheiro online</h1>
            <p>Este e-Book vai te mostrar 10 passos para te ajudar a iniciar na área de marketing digital de uma vez por todas.</p>
          </div>
          <div className={styles.contador}>
            <Countdown date={Date.now() + getTime()} precision={3} />
          </div>
          <form onSubmit={handleSubmit} method="post">
            <input type="text" onChange={onChangeEmail} id="email" name="email" placeholder='Seu melhor e-mail' />
            <span id='error-email' className={styles.error}></span>
            <input type="submit" value="QUERO RECEBER MEU E-BOOK" />
          </form>
        </div>
      </main>

      <footer>
        {/* <Link href="/">
          <a target='_blank'>Visite-nos</a>
        </Link>
        <span className={styles.divider} />
        <Link href="/politica_privacidade">
          <a target='_blank'>Política de Privacidade</a>
        </Link>
        <span className={styles.divider} />
        <Link href="/termo_uso">
          <a target='_blank'>Termo de uso</a>
        </Link> */}
      </footer>
    </div>
  )
}
