import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/SucessoEbook.module.scss'

export default function Sucesso() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Download E-book Grátis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.imgHeader}>
        <img src="/images/header-mari.jpg" alt="image" className={styles.image}></img>
      </header>

      <main className={styles.mensagem}>
        <h2>Parabéns!</h2>
        <p>Seu e-book está prontinho te esperando em seu e-mail!</p>
        <p>Corre lá, e bons estudos!</p>
      </main>

      <footer>
        <Link href="https://www.facebook.com/Mari-Rafaelle-109979308239231">
          <a target='_blank'>Facebook</a>
        </Link>
        <span className={styles.divider} />
        <Link href="https://www.instagram.com/marirafaelle/">
          <a target='_blank'>Instagram</a>
        </Link>
      </footer>
    </div>
  )
}
